on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - run: npm ci

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4
      - name: Restore npm cache
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - run: npm ci
      - run: npm run build

      - name: Run sshpass commands
        uses: matheusvanzan/sshpass-action@v2
        with:
          host: ${{ secrets.HOST_IP }}
          user: ${{ secrets.HOST_USER }}
          pass: ${{ secrets.HOST_PASSWORD }}
          run: |
            cd /root/hello-docker
            git pull
            # here

      - name: Deploy build artifacts to VPS
        run: |
          scp -r ./dist/* root@${{ secrets.HOST_IP }}:/root/hello-docker/static/
        env:
          HOME: /home/runner